baseURL = "gilbertek.github.io"
languageCode = "en-us"
title = "Prosightful"

relativeURLs = true
canonifyURLs = true

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/:filename/"
  pages = "/:filename/"
  tags = "/tag/:slug/"

[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About Us"
    identifier = "about"
    url = "/about/"
    weight = 2

[params]
  description="My home on the internet"

[outputFormats]
  [outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"
