baseURL = "https://prosightful.org"
languageCode = "en-us"
title = "ProSightful Counseling"

relativeURLs = true
canonifyURLs = true

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/:filename/"
  pages = "/:filename/"
  tags = "/tag/:slug/"

[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About Us"
    identifier = "about"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Services"
    identifier = "services"
    url = "/services/"
    weight = 3
  [[menu.main]]
    name = "Our Specialty"
    identifier = "specialty"
    url = "/specialty/"
    weight = 4
  [[menu.main]]
    name = "Contact Us"
    identifier = "contact"
    url = "/contact/"
    weight = 5


[params]
  description= "A Counseling firm based out of Omaha. Our therapists provide individual counseling, couple therapy, family counseling and group counseling. Serving all Omaha and neighboring cities."
  keywords = "Counseling, Individual Counseling, Couple Therapy, Family Counseling, Group Counseling, Gerald Igboanusi, MS, LMHP, LPC, NCC, Provisionally Licensed Mental Health Practitioner, Licensed Professional Counselor, Omaha, Nebraska"

[outputFormats]
  [outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"
