[build]
command = "npm run build"
publish = "assets"

[context.production.environment]
HUGO_VERSION = "0.55.6"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "npm run build"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.6"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
